
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.neftxx.interpreter.jflex_cup;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int PAR_DER = 41;
  public static final int DIFERENTE_QUE = 23;
  public static final int FUNCTION = 3;
  public static final int LIT_DECIMAL = 16;
  public static final int MULT = 29;
  public static final int CASE = 9;
  public static final int DOS_PUNTOS = 36;
  public static final int CONTINUE = 2;
  public static final int COR_DER = 43;
  public static final int FOR = 11;
  public static final int LLAVE_IZQ = 46;
  public static final int NOT = 39;
  public static final int AND = 38;
  public static final int IGUAL = 32;
  public static final int OR = 37;
  public static final int IN = 12;
  public static final int DIV = 30;
  public static final int UMENOS = 48;
  public static final int IF = 14;
  public static final int PUNTO_COMA = 44;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int LAMBDA = 21;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int LIT_STRING = 18;
  public static final int MODULO = 26;
  public static final int MENOS = 28;
  public static final int NULL = 20;
  public static final int MAYOR_QUE = 33;
  public static final int LIT_BOOLEANO = 17;
  public static final int PAR_IZQ = 40;
  public static final int BREAK = 7;
  public static final int SWITCH = 6;
  public static final int POTENCIA = 31;
  public static final int INTERROGANTE = 35;
  public static final int ELSE = 10;
  public static final int LLAVE_DER = 47;
  public static final int WHILE = 8;
  public static final int MAYOR_IGUAL_QUE = 24;
  public static final int IGUAL_QUE = 22;
  public static final int DEFAULT = 4;
  public static final int COR_IZQ = 42;
  public static final int LIT_ENTERO = 15;
  public static final int MENOR_QUE = 34;
  public static final int MENOR_IGUAL_QUE = 25;
  public static final int DO = 13;
  public static final int MAS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONTINUE",
  "FUNCTION",
  "DEFAULT",
  "RETURN",
  "SWITCH",
  "BREAK",
  "WHILE",
  "CASE",
  "ELSE",
  "FOR",
  "IN",
  "DO",
  "IF",
  "LIT_ENTERO",
  "LIT_DECIMAL",
  "LIT_BOOLEANO",
  "LIT_STRING",
  "ID",
  "NULL",
  "LAMBDA",
  "IGUAL_QUE",
  "DIFERENTE_QUE",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "MODULO",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "IGUAL",
  "MAYOR_QUE",
  "MENOR_QUE",
  "INTERROGANTE",
  "DOS_PUNTOS",
  "OR",
  "AND",
  "NOT",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "PUNTO_COMA",
  "COMA",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "UMENOS"
  };
}

